services:

  mongo:
    image: mongo:latest
    env_file:
      - .env
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: MONGODB_PASSWORD
